micronaut:
  application:
    name: demo
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    schema-generate: CREATE_DROP
    dialect: H2
#  users:
#    driverClassName: org.postgresql.Driver
#    schema-generate: CREATE_DROP
#    dialect: POSTGRES