micronaut.application.name=library

datasources.default.dialect=MYSQL
datasources.default.db-type=mysql
datasources.default.driverClassName=com.mysql.cj.jdbc.Driver

flyway.datasources.default.enabled=true